version: '3'
services:
  trading-app:
    restart: always
    build: .
    container_name: 'trading-app'
    ports:
      - "8001:8001"
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/src/
      - ~/.zshrc:/root/.zshrc
